/**
 * Unit tests for qrCode utility functions.
 *
 * getNetworkConfig() and isValidAccountId() are imported from blockchain.ts which
 * calls into native modules at import time.  We mock the whole module so we can
 * run these tests in a plain Node environment.
 */

jest.mock('../../services/blockchain', () => ({
  getNetworkConfig: () => ({
    network: 'testnet',
    assetCode: 'CPINR',
    assetIssuer: 'GA2SFZ4GJVMLPULSJMTY7RMIOPQD5W5JGTDSD3N7I2PR5KZRFGPQF5BJ',
  }),
  isValidAccountId: (id: string) =>
    /^G[A-Z2-7]{55}$/.test(id),
}));

// Suppress expected error-path console.error messages so test output stays clean.
beforeAll(() => {
  jest.spyOn(console, 'error').mockImplementation(() => {});
});

afterAll(() => {
  jest.restoreAllMocks();
});

import {
  generatePaymentQR,
  parsePaymentQR,
  validatePaymentQR,
  generatePaymentQRWithId,
  type PaymentQRData,
} from '../../utils/qrCode';

const VALID_MERCHANT = 'GBGJS2UIEF2DYN3L67P2A7X62M4WK72JGTF7ABCOQL75UYHMWYLFRI4S';
const VALID_MERCHANT_ID = 'merchant-abc-123';
const VALID_ISSUER = 'GA2SFZ4GJVMLPULSJMTY7RMIOPQD5W5JGTDSD3N7I2PR5KZRFGPQF5BJ';

describe('generatePaymentQR', () => {
  test('produces a JSON string parseable back to a PaymentQRData object', () => {
    const qr = generatePaymentQR(VALID_MERCHANT, '100', 'Test Merchant');
    const data = JSON.parse(qr);
    expect(data.type).toBe('cryptopay');
    expect(data.version).toBe(2);
    expect(data.merchant).toBe(VALID_MERCHANT);
    expect(data.amount).toBe('100');
    expect(data.name).toBe('Test Merchant');
  });

  test('includes network, assetCode, and assetIssuer from config', () => {
    const qr = generatePaymentQR(VALID_MERCHANT, '50', 'Shop');
    const data = JSON.parse(qr);
    expect(data.network).toBe('stellar-testnet');
    expect(data.assetCode).toBe('CPINR');
    expect(data.assetIssuer).toBe(VALID_ISSUER);
  });

  test('includes an optional note when provided', () => {
    const qr = generatePaymentQR(VALID_MERCHANT, '20', 'Shop', 'Invoice #42');
    const data = JSON.parse(qr);
    expect(data.note).toBe('Invoice #42');
  });

  test('note is omitted when not provided', () => {
    const qr = generatePaymentQR(VALID_MERCHANT, '20', 'Shop');
    const data = JSON.parse(qr);
    expect(data.note).toBeUndefined();
  });
});

describe('generatePaymentQRWithId', () => {
  test('includes merchantId field in QR payload', () => {
    const qr = generatePaymentQRWithId(VALID_MERCHANT_ID, '75', 'My Store', VALID_MERCHANT);
    const data = JSON.parse(qr);
    expect(data.merchantId).toBe(VALID_MERCHANT_ID);
    expect(data.merchant).toBe(VALID_MERCHANT);
  });
});

describe('parsePaymentQR', () => {
  function makeValidQR(overrides: Partial<PaymentQRData> = {}): string {
    return JSON.stringify({
      type: 'cryptopay',
      version: 2,
      network: 'stellar-testnet',
      merchant: VALID_MERCHANT,
      assetCode: 'CPINR',
      assetIssuer: VALID_ISSUER,
      amount: '100',
      name: 'Test Shop',
      ...overrides,
    });
  }

  test('returns a PaymentQRData object for a valid QR string', () => {
    const data = parsePaymentQR(makeValidQR());
    expect(data).not.toBeNull();
    expect(data?.type).toBe('cryptopay');
    expect(data?.merchant).toBe(VALID_MERCHANT);
  });

  test('round-trips QR generated by generatePaymentQR', () => {
    const qr = generatePaymentQR(VALID_MERCHANT, '100', 'Merchant');
    const data = parsePaymentQR(qr);
    expect(data).not.toBeNull();
    expect(data?.amount).toBe('100');
  });

  test('returns null for invalid JSON', () => {
    expect(parsePaymentQR('not-json')).toBeNull();
  });

  test('returns null when required fields are missing', () => {
    expect(parsePaymentQR(makeValidQR({ merchant: undefined as any }))).toBeNull();
    expect(parsePaymentQR(makeValidQR({ amount: undefined as any }))).toBeNull();
    expect(parsePaymentQR(makeValidQR({ name: undefined as any }))).toBeNull();
    expect(parsePaymentQR(makeValidQR({ assetCode: undefined as any }))).toBeNull();
    expect(parsePaymentQR(makeValidQR({ assetIssuer: undefined as any }))).toBeNull();
  });

  test('returns null when type is not "cryptopay"', () => {
    expect(parsePaymentQR(makeValidQR({ type: 'other' as any }))).toBeNull();
  });

  test('returns null when version is not 2', () => {
    expect(parsePaymentQR(makeValidQR({ version: 1 as any }))).toBeNull();
  });
});

describe('validatePaymentQR', () => {
  function validData(): PaymentQRData {
    return {
      type: 'cryptopay',
      version: 2,
      network: 'stellar-testnet',
      merchant: VALID_MERCHANT,
      assetCode: 'CPINR',
      assetIssuer: VALID_ISSUER,
      amount: '100',
      name: 'Test Shop',
    };
  }

  test('accepts a fully valid QR payload', () => {
    expect(validatePaymentQR(validData())).toEqual({ valid: true });
  });

  test('accepts zero amount (variable-amount merchant QR)', () => {
    expect(validatePaymentQR({ ...validData(), amount: '0' })).toEqual({ valid: true });
  });

  test('rejects an invalid merchant account ID', () => {
    const result = validatePaymentQR({ ...validData(), merchant: 'not-a-stellar-account' });
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/merchant/i);
  });

  test('rejects a wrong network', () => {
    const result = validatePaymentQR({ ...validData(), network: 'stellar-mainnet' });
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/network/i);
  });

  test('rejects a wrong asset code', () => {
    const result = validatePaymentQR({ ...validData(), assetCode: 'USDC' });
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/asset/i);
  });

  test('rejects a wrong asset issuer', () => {
    const result = validatePaymentQR({ ...validData(), assetIssuer: VALID_MERCHANT });
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/asset/i);
  });

  test('rejects a negative amount', () => {
    const result = validatePaymentQR({ ...validData(), amount: '-10' });
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/amount/i);
  });

  test('rejects a non-numeric amount', () => {
    const result = validatePaymentQR({ ...validData(), amount: 'abc' });
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/amount/i);
  });

  test('rejects an empty merchant name', () => {
    const result = validatePaymentQR({ ...validData(), name: '   ' });
    expect(result.valid).toBe(false);
    expect(result.error).toMatch(/name/i);
  });
});
